// C# 인터프리터 단위 테스트 (OpenCV 없이): node tools/cstest.mjs [필터]
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
require(path.join(here, '../js/cs-lang.js'));
require(path.join(here, '../js/cs-runtime.js'));
require(path.join(here, '../js/cs-stdlib.js'));
const { Interpreter, CsException } = globalThis.CsRuntime;

function run(code, stdin = '') {
  let out = '';
  const lines = stdin.split('\n');
  const host = { write: (s, t) => { out += t; }, readLine: () => (lines.length ? lines.shift() : null), checkStop: () => {}, sleep: () => {} };
  const it = new Interpreter(host);
  try { const r = it.run(code); return { out, exit: r.exit }; }
  catch (e) { return { out, error: e instanceof CsException ? `${e.csType}: ${e.csMessage}` : (e.name === 'CsSyntaxError' ? `Syntax(${e.line}:${e.col}): ${e.message}` : 'JS ' + (e.stack || e)) }; }
}

const tests = [];
const t = (name, code, expect, stdin) => tests.push({ name, code, expect, stdin });

t('hello', `using System;\nclass Program { static void Main() { Console.WriteLine("Hello, OpenCV!"); } }`, 'Hello, OpenCV!\n');
t('toplevel', `Console.WriteLine(1 + 2 * 3);`, '7\n');
t('intdiv', `int a = 7, b = 2; Console.WriteLine(a / b); Console.WriteLine(a / 2.0); Console.WriteLine((double)a / b); Console.WriteLine(7 % 3); double d = 4; Console.WriteLine(d / 3);`, '3\n3.5\n3.5\n1\n1.3333333333333333\n');
t('interp', `int n = 5; double x = 3.14159; string s = "abc"; Console.WriteLine($"n={n}, x={x:F2}, s={s,5}|{s,-5}|, {n * 2}");`, 'n=5, x=3.14, s=  abc|abc  |, 10\n');
t('format', `Console.WriteLine("{0} + {1} = {2}", 1, 2, 3); Console.WriteLine(string.Format("{0:N0} {1:X2} {2:P1} {3:D3} {4:0.00}", 1234567, 255, 0.256, 7, 3.14159)); Console.WriteLine(3.0); Console.WriteLine(1.5f); Console.WriteLine(0.1 + 0.2); Console.WriteLine(1e20); Console.WriteLine((2.5).ToString("F0")); Console.WriteLine(Math.Round(2.5)); Console.WriteLine(Math.Round(3.5)); Console.WriteLine(Math.Round(2.345, 2)); Console.WriteLine(Math.Round(2.5, MidpointRounding.AwayFromZero));`, '1 + 2 = 3\n1,234,567 FF 25.6% 007 3.14\n3\n1.5\n0.30000000000000004\n1E+20\n3\n2\n4\n2.34\n3\n');
t('loops', `int sum = 0; for (int i = 1; i <= 10; i++) { if (i % 2 == 0) continue; sum += i; } Console.WriteLine(sum); int k = 0; while (true) { k++; if (k > 3) break; } Console.WriteLine(k); do { k--; } while (k > 0); Console.WriteLine(k); foreach (var c in "ab") Console.Write(c); Console.WriteLine();`, '25\n4\n0\nab\n');
t('arrays', `int[] a = { 3, 1, 2 }; Array.Sort(a); Console.WriteLine(string.Join(",", a)); var b = new int[3]; b[1] = 5; Console.WriteLine(b.Length + " " + b[1]); int[,] g = new int[2, 3]; g[1, 2] = 9; Console.WriteLine(g[1, 2] + " " + g.GetLength(1)); int[][] j = new int[2][]; j[0] = new[] { 1, 2 }; Console.WriteLine(j[0][1]); byte[] bs = new byte[2]; bs[0] = (byte)300; Console.WriteLine(bs[0]); var names = new string[] { "x", "y" }; Console.WriteLine(names[^1]);`, '1,2,3\n3 5\n9 3\n2\n44\ny\n');
t('list-dict', `var list = new List<int> { 5, 2, 8 }; list.Add(1); list.Sort(); Console.WriteLine(string.Join(" ", list)); Console.WriteLine(list.Count + " " + list[0]); var d = new Dictionary<string, int>(); d["a"] = 1; d["b"] = 2; d["a"]++; foreach (var kv in d) Console.WriteLine($"{kv.Key}={kv.Value}"); if (d.TryGetValue("b", out int v)) Console.WriteLine(v); Console.WriteLine(d.ContainsKey("z")); foreach (var (k, val) in d) Console.Write(k + val); Console.WriteLine();`, '1 2 5 8\n4 1\na=2\nb=2\n2\nFalse\na2b2\n');
t('linq', `using System.Linq; var xs = new[] { 5, 3, 8, 1 }; var ev = xs.Where(x => x > 2).OrderBy(x => x).Select(x => x * 10).ToList(); Console.WriteLine(string.Join(",", ev)); Console.WriteLine(xs.Sum() + " " + xs.Max() + " " + xs.Average() + " " + xs.Count(x => x > 4)); Console.WriteLine(xs.First() + " " + xs.Last() + " " + xs.Any(x => x == 8)); var words = new List<string> { "bb", "a", "ccc" }; Console.WriteLine(string.Join(",", words.OrderByDescending(w => w.Length))); var g = xs.GroupBy(x => x % 2); foreach (var grp in g) Console.WriteLine(grp.Key + ": " + grp.Count()); Console.WriteLine(Enumerable.Range(1, 5).Select(i => i * i).Sum()); Console.WriteLine(xs.Select((x, i) => x * i).Sum());`, '30,50,80\n17 8 4.25 2\n5 1 True\nccc,bb,a\n1: 3\n0: 1\n55\n22\n');
t('class', `class Point2 { public int X { get; set; } public int Y; public Point2(int x, int y) { X = x; Y = y; } public double Len => Math.Sqrt(X * X + Y * Y); public override string ToString() => $"({X}, {Y})"; public static Point2 operator +(Point2 a, Point2 b) => new Point2(a.X + b.X, a.Y + b.Y); }
class Animal { public virtual string Speak() { return "..."; } public string Name = "animal"; }
class Dog : Animal { public override string Speak() { return "Woof"; } }
var p = new Point2(3, 4); Console.WriteLine(p.Len); Console.WriteLine(p); Console.WriteLine(p + new Point2(1, 1)); Animal a = new Dog(); Console.WriteLine(a.Speak() + " " + a.Name); var q = new Point2(0, 0) { X = 7 }; Console.WriteLine(q.X);`, '5\n(3, 4)\n(4, 5)\nWoof animal\n7\n');
t('struct-enum', `struct Vec { public double X, Y; public Vec(double x, double y) { X = x; Y = y; } } enum Color { Red, Green = 5, Blue } Vec v = new Vec(1, 2); Vec w = v; w.X = 9; Console.WriteLine(v.X + " " + w.X); Color c = Color.Blue; Console.WriteLine(c + " " + (int)c + " " + (Color)5); Console.WriteLine(c == Color.Blue);`, '1 9\nBlue 6 Green\nTrue\n');
t('switch', `int n = 3; switch (n) { case 1: Console.WriteLine("one"); break; case 2: case 3: Console.WriteLine("two-three"); break; default: Console.WriteLine("many"); break; } string s = n switch { 1 => "a", 3 => "c", _ => "?" }; Console.WriteLine(s); object o = 4.5; switch (o) { case int i: Console.WriteLine("int " + i); break; case double d when d > 4: Console.WriteLine("big double " + d); break; } Console.WriteLine(n is > 2 and < 5);`, 'two-three\nc\nbig double 4.5\nTrue\n');
t('exceptions', `try { int[] a = new int[2]; a[5] = 1; } catch (IndexOutOfRangeException e) { Console.WriteLine("범위: " + e.Message.Substring(0, 5)); } finally { Console.WriteLine("finally"); } try { int z = 0; Console.WriteLine(10 / z); } catch (DivideByZeroException) { Console.WriteLine("div0"); } try { throw new ArgumentException("bad arg"); } catch (Exception ex) { Console.WriteLine(ex.GetType().Name + ": " + ex.Message); } try { int.Parse("abc"); } catch (FormatException) { Console.WriteLine("format"); } class MyEx : Exception { public MyEx(string m) : base(m) {} } try { throw new MyEx("custom"); } catch (MyEx e) { Console.WriteLine(e.Message); }`, '범위: Index\nfinally\ndiv0\nArgumentException: bad arg\nformat\ncustom\n');
t('strings', `string s = "Hello, World"; Console.WriteLine(s.ToUpper() + " " + s.Length + " " + s.IndexOf("World") + " " + s.Substring(7) + " " + s.Replace("l", "L") + " " + s.Contains("lo")); var parts = "a,b,,c".Split(','); Console.WriteLine(parts.Length); Console.WriteLine(string.Join("|", "a b  c".Split(' ', StringSplitOptions.RemoveEmptyEntries))); char c = s[0]; Console.WriteLine(c + " " + (int)c + " " + (char)(c + 1) + " " + char.IsUpper(c)); Console.WriteLine("abc".PadLeft(5, '*') + "|" + " x ".Trim() + "|"); var sb = new System.Text.StringBuilder(); sb.Append("a").Append(1).AppendLine("b"); Console.Write(sb.ToString()); Console.WriteLine(@"C:\\path" + "\\n".Length); Console.WriteLine($"{"nested"}");`, 'HELLO, WORLD 12 7 World HeLLo, WorLd True\n4\na|b|c\nH 72 I True\n**abc|x|\na1b\nC:\\path1\nnested\n');
t('methods', `static int Fib(int n) => n < 2 ? n : Fib(n - 1) + Fib(n - 2); static void Swap(ref int a, ref int b) { int t = a; a = b; b = t; } static bool TryHalf(int n, out int half) { half = n / 2; return n % 2 == 0; } static int Sum(params int[] xs) { int s = 0; foreach (var x in xs) s += x; return s; } static double Area(double r, double pi = 3.0) => pi * r * r; Console.WriteLine(Fib(10)); int p = 1, q = 2; Swap(ref p, ref q); Console.WriteLine(p + " " + q); if (TryHalf(8, out var h)) Console.WriteLine(h); Console.WriteLine(Sum(1, 2, 3) + " " + Sum()); Console.WriteLine(Area(2) + " " + Area(2, pi: 3.14)); Func<int, int> sq = x => x * x; Action<string> say = m => Console.WriteLine("say " + m); Console.WriteLine(sq(6)); say("hi"); int Local(int x) { return x + 1; } Console.WriteLine(Local(1));`, '55\n2 1\n4\n6 0\n12 12.56\n36\nsay hi\n2\n');
t('readline', `Console.Write("이름: "); string name = Console.ReadLine(); int age = int.Parse(Console.ReadLine()); Console.WriteLine($"{name}님은 {age}살"); Console.WriteLine(Console.ReadLine() == null);`, '이름: 철수님은 20살\nTrue\n', '철수\n20');
t('tuples', `(int a, string b) t = (1, "x"); Console.WriteLine(t.a + t.b); var (x, y) = (3, 4); Console.WriteLine(x * y); static (double, double) MinMax(int[] arr) => (arr.Min(), arr.Max()); var mm = MinMax(new[] { 4, 9, 2 }); Console.WriteLine(mm.Item1 + " " + mm.Item2); (x, y) = (y, x); Console.WriteLine(x + "," + y);`, '1x\n12\n2 9\n4,3\n');
t('generics-user', `class Box<T> { public T Value; public Box(T v) { Value = v; } public T Get() => Value; } var b = new Box<int>(5); Console.WriteLine(b.Get() + 1); var bs = new Box<string>("s"); Console.WriteLine(bs.Value.Length);`, '6\n1\n');
t('math-casts', `Console.WriteLine((int)3.99 + " " + (int)-3.99 + " " + (byte)257 + " " + (char)65 + " " + (int)'a'); Console.WriteLine(Math.Max(3, 7) + " " + Math.Abs(-2.5) + " " + Math.Pow(2, 10) + " " + Math.Sqrt(16) + " " + Math.PI.ToString("F4")); long big = 3000000000; Console.WriteLine(big * 2); int x = int.MaxValue; x++; Console.WriteLine(x); Console.WriteLine(10 / 4 * 4 + 10 % 4); Console.WriteLine(1 << 10); Console.WriteLine(0xFF & 0x0F); Console.WriteLine(5 / 2 + 5.0 / 2);`, '3 -3 1 A 97\n7 2.5 1024 4 3.1416\n6000000000\n-2147483648\n10\n1024\n15\n4.5\n');
t('nullable', `int? n = null; Console.WriteLine(n.HasValue); n ??= 5; Console.WriteLine(n.Value + 1); string s = null; Console.WriteLine(s?.Length ?? -1); Console.WriteLine((s ?? "def").Length); List<int> l = null; Console.WriteLine(l?.Count);`, 'False\n6\n-1\n3\n\n');
t('static-class', `static class Util { public static int Counter = 0; public const double Rate = 1.5; public static int Next() => ++Counter; } Util.Next(); Util.Next(); Console.WriteLine(Util.Counter + " " + Util.Rate); using static System.Math; Console.WriteLine(Sqrt(9));`, '2 1.5\n3\n');
t('verbatim-interp', `int w = 640, h = 480; Console.WriteLine($@"size {w}x{h} \\ ok"); Console.WriteLine($"{{literal}} {w,-6}|"); Console.WriteLine($"{(w > h ? "landscape" : "portrait")}"); Console.WriteLine($"{w / 2.0:F1} {h:D5}");`, 'size 640x480 \\ ok\n{literal} 640   |\nlandscape\n320.0 00480\n');
t('interface-abstract', `interface IShape { double Area(); } abstract class Shape : IShape { public abstract double Area(); public string Info() => $"{GetType().Name} {Area():F1}"; } class Sq : Shape { double s; public Sq(double s) { this.s = s; } public override double Area() => s * s; } class Ci : Shape { double r; public Ci(double r) => this.r = r; public override double Area() => Math.PI * r * r; } var shapes = new List<Shape> { new Sq(2), new Ci(1) }; foreach (var sh in shapes) Console.WriteLine(sh.Info()); Console.WriteLine(shapes.Sum(s => s.Area()).ToString("F2")); IShape i = shapes[0]; Console.WriteLine(i is Sq);`, 'Sq 4.0\nCi 3.1\n7.14\nTrue\n');
t('stopwatch-random', `var sw = System.Diagnostics.Stopwatch.StartNew(); var rnd = new Random(42); int a = rnd.Next(10), b = rnd.Next(10); Console.WriteLine(a >= 0 && a < 10 && b >= 0 && b < 10); sw.Stop(); Console.WriteLine(sw.ElapsedMilliseconds >= 0);`, 'True\nTrue\n');
t('foreach-list-modify-error', `var l = new List<int> { 1, 2 }; int total = 0; foreach (var x in l) total += x; Console.WriteLine(total); var q = new Queue<string>(); q.Enqueue("a"); q.Enqueue("b"); Console.WriteLine(q.Dequeue() + q.Count); var st = new Stack<int>(); st.Push(1); st.Push(2); Console.WriteLine(st.Pop() + st.Peek()); var hs = new HashSet<int> { 1, 1, 2 }; Console.WriteLine(hs.Count);`, '3\na1\n3\n2\n');
t('char-arith', `char c = 'a'; c++; Console.WriteLine(c); Console.WriteLine(c + 1); Console.WriteLine((char)(c + 1)); string s = ""; for (char ch = 'a'; ch <= 'e'; ch++) s += ch; Console.WriteLine(s); Console.WriteLine('x' == 'x'); int cnt = 0; foreach (char ch in "hello") if (ch == 'l') cnt++; Console.WriteLine(cnt); Console.WriteLine("abc"[1]); Console.WriteLine(char.ToUpper('q'));`, 'b\n99\nc\nabcde\nTrue\n2\nb\nQ\n');
t('property-full', `class Temp { private double c; public double Celsius { get { return c; } set { if (value < -273.15) throw new ArgumentOutOfRangeException("value"); c = value; } } public double F => c * 9 / 5 + 32; public int Count { get; private set; } = 3; } var t = new Temp(); t.Celsius = 100; Console.WriteLine(t.F + " " + t.Count); try { t.Celsius = -300; } catch (ArgumentOutOfRangeException) { Console.WriteLine("range"); }`, '212 3\nrange\n');
t('errors-msg', `int x = "5";`, null);
t('syntax-err', `Console.WriteLine("hi")`, null);
t('main-args-return', `class P { static int Main(string[] args) { Console.WriteLine(args.Length); return 3; } }`, '0\n');
t('goto-less-while', `int i = 0; int[] data = { 4, 8, 15 }; while (i < data.Length && data[i] < 10) i++; Console.WriteLine(i); Console.WriteLine(data.Contains(8) + " " + Array.IndexOf(data, 15));`, '2\nTrue 2\n');
t('delegate-multicast', `Action a = () => Console.Write("1"); a += () => Console.Write("2"); a(); Console.WriteLine(); Func<int, int, int> add = (x, y) => x + y; Console.WriteLine(add(2, 3)); var fs = new List<Func<int>>(); for (int i = 0; i < 3; i++) { int j = i; fs.Add(() => j * 10); } Console.WriteLine(string.Join(",", fs.Select(f => f())));`, '12\n5\n0,10,20\n');
t('const-readonly-static-ctor', `class C { public const int N = 3; public static readonly int[] Table; static C() { Table = new int[N]; for (int i = 0; i < N; i++) Table[i] = i * i; } } Console.WriteLine(string.Join(" ", C.Table));`, '0 1 4\n');
t('using-dispose', `class Res : IDisposable { public string Name; public Res(string n) { Name = n; Console.WriteLine("open " + n); } public void Dispose() { Console.WriteLine("close " + Name); } } using (var r = new Res("A")) { Console.WriteLine("use " + r.Name); } using var r2 = new Res("B"); Console.WriteLine("end");`, 'open A\nuse A\nclose A\nopen B\nend\nclose B\n');
t('2d-init', `int[,] m = { { 1, 2, 3 }, { 4, 5, 6 } }; int s = 0; for (int r = 0; r < m.GetLength(0); r++) for (int c = 0; c < m.GetLength(1); c++) s += m[r, c]; Console.WriteLine(s + " " + m.Length); double[] k = { 1, 2 }; Console.WriteLine(k[0] / 2);`, '21 6\n0.5\n');

const filter = process.argv[2];
let pass = 0, fail = 0;
for (const tc of tests) {
  if (filter && !tc.name.includes(filter)) continue;
  const r = run(tc.code, tc.stdin || '');
  const ok = tc.expect == null ? !!r.error : r.out === tc.expect && !r.error;
  if (ok) pass++; else { fail++; console.log(`✗ ${tc.name}\n  기대: ${JSON.stringify(tc.expect)}\n  실제: ${JSON.stringify(r.out)}${r.error ? '\n  오류: ' + r.error : ''}`); }
  if (tc.expect == null && r.error && !filter) console.log(`  (${tc.name}) 오류 메시지: ${r.error}`);
}
console.log(`\n${pass} 통과, ${fail} 실패`);
process.exit(fail ? 1 : 0);
