// 강좌 코드에서 자주 쓰일 C# 패턴 추가 테스트 (OpenCV 포함): node tools/cstest2.mjs [필터]
import { runCs } from './node-host.mjs';
const tests = [];
const t = (name, code, expect) => tests.push({ name, code, expect });
const U = 'using System;\nusing System.Linq;\nusing System.Collections.Generic;\nusing OpenCvSharp;\n';

t('select-index-tuple', U + `var xs = new[] { "a", "b", "c" }; foreach (var (s, i) in xs.Select((s, i) => (s, i))) Console.WriteLine($"{i}:{s}"); Console.WriteLine(string.Join(", ", xs.Select((s, i) => $"{i}={s}")));`, '0:a\n1:b\n2:c\n0=a, 1=b, 2=c\n');
t('static-fields-methods', U + `class Program { static int Count = 0; const double Scale = 0.1; static readonly string[] Names = { "S", "M", "L" }; static string Grade(double r) { if (r < 24) return Names[0]; if (r < 31) return Names[1]; return Names[2]; } static void Main() { foreach (var r in new double[] { 20, 27, 34 }) { Count++; Console.WriteLine($"{r * Scale:F1} mm → {Grade(r)}"); } Console.WriteLine(Count); } }`, '2.0 mm → S\n2.7 mm → M\n3.4 mm → L\n3\n');
t('array-sort-lambda', U + `var pts = new[] { new Point(3, 1), new Point(1, 5), new Point(2, 2) }; Array.Sort(pts, (a, b) => a.X.CompareTo(b.X)); Console.WriteLine(string.Join(" ", pts.Select(p => p.X))); var list = pts.ToList(); list.Sort((a, b) => b.Y - a.Y); Console.WriteLine(list[0]); var byLen = pts.OrderBy(p => Math.Sqrt(p.X * p.X + p.Y * p.Y)).First(); Console.WriteLine(byLen);`, '1 2 3\n(x:1 y:5)\n(x:2 y:2)\n');
t('enum-switch', U + `enum Filter { None, Gray, Blur, Canny } class Program { static Mat Apply(Mat src, Filter f) { switch (f) { case Filter.Gray: return src.CvtColor(ColorConversionCodes.BGR2GRAY); case Filter.Blur: return src.GaussianBlur(new Size(5, 5), 0); case Filter.Canny: { var g = src.CvtColor(ColorConversionCodes.BGR2GRAY); return g.Canny(50, 150); } default: return src.Clone(); } } static void Main() { using var img = Cv2.ImRead("images/sample_color.png"); foreach (Filter f in Enum.GetValues(typeof(Filter))) { var r = Apply(img, f); Console.WriteLine($"{f}: {r.Channels()}ch {r.Type()}"); } } }`, 'None: 3ch CV_8UC3\nGray: 1ch CV_8UC1\nBlur: 3ch CV_8UC3\nCanny: 1ch CV_8UC1\n');
t('dictionary-count-colors', U + `var counts = new Dictionary<string, int> { ["red"] = 0, ["green"] = 0 }; counts["red"] += 3; counts["green"]++; foreach (var kv in counts.OrderByDescending(k => k.Value)) Console.WriteLine($"{kv.Key,-6}{kv.Value,3}"); Console.WriteLine(counts.Values.Sum()); if (!counts.ContainsKey("blue")) counts["blue"] = 1; Console.WriteLine(counts.Count);`, 'red     3\ngreen   1\n4\n3\n');
t('class-result-record', U + `class CountResult { public int Count { get; set; } public bool Ok => Count == Expected; public int Expected { get; set; } public List<Rect> Boxes { get; } = new List<Rect>(); public override string ToString() => $"{(Ok ? "OK" : "NG")} {Count}/{Expected}"; } record Blob2(int Label, double Area); class Program { static void Main() { var r = new CountResult { Expected = 3 }; r.Boxes.Add(new Rect(0, 0, 10, 10)); r.Boxes.Add(new Rect(5, 5, 10, 10)); r.Count = r.Boxes.Count; Console.WriteLine(r); var b = new Blob2(1, 250.5); Console.WriteLine(b); Console.WriteLine(b.Area > 100); } }`, 'NG 2/3\nBlob2 { Label = 1, Area = 250.5 }\nTrue\n');
t('contours-pipeline', U + `class Program { static void Main() { using var img = Cv2.ImRead("images/coins_parts.png", ImreadModes.Grayscale); using var bin = img.Threshold(0, 255, ThresholdTypes.Binary | ThresholdTypes.Otsu); Point[][] contours = Cv2.FindContoursAsArray(bin, RetrievalModes.External, ContourApproximationModes.ApproxSimple); var big = contours.Where(c => Cv2.ContourArea(c) > 500).ToList(); using var color = img.CvtColor(ColorConversionCodes.GRAY2BGR); int i = 0; foreach (var c in big) { var r = Cv2.BoundingRect(c); Cv2.Rectangle(color, r, Scalar.Red, 2); var m = Cv2.Moments(c); var cx = (int)(m.M10 / m.M00); var cy = (int)(m.M01 / m.M00); Cv2.PutText(color, (++i).ToString(), new Point(cx - 8, cy + 8), HersheyFonts.HersheySimplex, 0.6, Scalar.Yellow, 2); } Console.WriteLine(big.Count); double avgR = big.Average(c => Math.Sqrt(Cv2.ContourArea(c) / Math.PI)); Console.WriteLine($"{avgR:F1}"); Cv2.ImShow("r", color); } }`, '12\n25.3\n');
t('hierarchy-holes', U + `using var img = Cv2.ImRead("images/flange.png", ImreadModes.Grayscale); using var bin = img.Threshold(0, 255, ThresholdTypes.Binary | ThresholdTypes.Otsu); Cv2.FindContours(bin, out Point[][] cs, out HierarchyIndex[] h, RetrievalModes.CComp, ContourApproximationModes.ApproxSimple); int holes = h.Count(x => x.Parent >= 0); Console.WriteLine(holes);`, '7\n');
t('mat-from-array-kernel', U + `var k = new Mat(3, 3, MatType.CV_32FC1, new float[] { 0, -1, 0, -1, 5, -1, 0, -1, 0 }); Console.WriteLine(k.Dump()); using var img = Cv2.ImRead("images/sample_gray.png", ImreadModes.Grayscale); using var sharp = new Mat(); Cv2.Filter2D(img, sharp, MatType.CV_8U, k); Console.WriteLine(sharp.Size()); var kd = Mat.FromArray(new double[,] { { 1, 2 }, { 3, 4 } }); Console.WriteLine(kd.Rows + "x" + kd.Cols + " " + kd.Type()); var t = new Mat(2, 3, MatType.CV_64FC1, new double[] { 1, 0, 30, 0, 1, 20 }); using var moved = new Mat(); Cv2.WarpAffine(img, moved, t, img.Size()); Console.WriteLine(moved.Get<byte>(0, 0));`, '[0, -1, 0;\n -1, 5, -1;\n 0, -1, 0]\n(width:640 height:480)\n2x2 CV_64FC1\n0\n');
t('hist-draw', U + `using var img = Cv2.ImRead("images/low_contrast.png", ImreadModes.Grayscale); using var hist = new Mat(); Cv2.CalcHist(new[] { img }, new[] { 0 }, null, hist, 1, new[] { 256 }, new[] { new Rangef(0, 256) }); Cv2.MinMaxLoc(hist, out _, out double maxV); using var canvas = new Mat(200, 256, MatType.CV_8UC3, Scalar.White); for (int i = 0; i < 256; i++) { int hgt = (int)(hist.At<float>(i, 0) / maxV * 190); Cv2.Line(canvas, new Point(i, 199), new Point(i, 199 - hgt), Scalar.Black); } int nonEmpty = 0; for (int i = 0; i < 256; i++) if (hist.At<float>(i, 0) > 0) nonEmpty++; Console.WriteLine(nonEmpty); Cv2.ImShow("hist", canvas);`, '33\n');
t('string-format-table', U + `var rows = new List<(string name, int n, double area)> { ("W1", 3, 1234.5), ("N2", 12, 98.25) }; Console.WriteLine($"{"이름",-4}|{"개수",4}|{"면적",9}"); foreach (var (name, n, area) in rows) Console.WriteLine($"{name,-4}|{n,4}|{area,9:F1}"); Console.WriteLine(string.Format("{0}: {1:P0}", "비율", 0.5)); var csv = string.Join("\\n", rows.Select(r => $"{r.name},{r.n},{r.area}")); Console.WriteLine(csv);`, '이름  |  개수|       면적\nW1  |   3|   1234.5\nN2  |  12|     98.3\n비율: 50%\nW1,3,1234.5\nN2,12,98.25\n');
t('video-motion', U + `using var cap = new VideoCapture(0); using var frame = new Mat(); using var prev = new Mat(); int moving = 0, n = 0; while (cap.Read(frame) && n < 10) { n++; using var g = frame.CvtColor(ColorConversionCodes.BGR2GRAY); if (!prev.Empty()) { using var d = new Mat(); Cv2.Absdiff(g, prev, d); Cv2.Threshold(d, d, 30, 255, ThresholdTypes.Binary); if (Cv2.CountNonZero(d) > 100) moving++; } g.CopyTo(prev); } Console.WriteLine($"{n} {moving}");`, '10 9\n');
t('mog2', U + `using var cap = new VideoCapture(0); var mog = BackgroundSubtractorMOG2.Create(); using var frame = new Mat(); using var fg = new Mat(); int n = 0; while (cap.Read(frame) && n < 5) { n++; mog.Apply(frame, fg); } Console.WriteLine(fg.Type() + " " + (Cv2.CountNonZero(fg) >= 0));`, 'CV_8UC1 True\n');
t('try-parse-readline', U + `string s = Console.ReadLine(); if (int.TryParse(s, out int v)) Console.WriteLine(v * 2); else Console.WriteLine("숫자가 아닙니다"); var parts = "3,4".Split(','); var p = new Point(int.Parse(parts[0]), int.Parse(parts[1])); Console.WriteLine(p);`, '42\n(x:3 y:4)\n');
t('stopwatch-nondet', U + `var sw = System.Diagnostics.Stopwatch.StartNew(); using var img = Cv2.ImRead("images/sample_color.png"); using var b = img.GaussianBlur(new Size(9, 9), 0); sw.Stop(); Console.WriteLine(sw.ElapsedMilliseconds >= 0 ? "ok" : "bad"); Console.WriteLine($"{sw.Elapsed.TotalMilliseconds >= 0}");`, 'ok\nTrue\n');
t('rotated-rect-points', U + `using var img = Cv2.ImRead("images/chip_rotated.png", ImreadModes.Grayscale); using var bin = img.Threshold(0, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu); var cs = Cv2.FindContoursAsArray(bin, RetrievalModes.External, ContourApproximationModes.ApproxSimple); var body = cs.OrderByDescending(c => Cv2.ContourArea(c)).First(); RotatedRect rr = Cv2.MinAreaRect(body); Point2f[] pts = rr.Points(); Console.WriteLine(pts.Length); Console.WriteLine(rr.Size.Width > 50 && rr.Size.Height > 50); using var color = img.CvtColor(ColorConversionCodes.GRAY2BGR); for (int i = 0; i < 4; i++) Cv2.Line(color, (Point)pts[i], (Point)pts[(i + 1) % 4], Scalar.Red, 2); Cv2.Polylines(color, new[] { pts.Select(p => new Point(p.X, p.Y)).ToArray() }, true, Scalar.Lime, 1); Console.WriteLine(Math.Abs(rr.Angle) < 90);`, '4\nTrue\nTrue\n');
t('perspective-points', U + `var src = new[] { new Point2f(61.56f, 57.38f), new Point2f(583.83f, 65.15f), new Point2f(574.58f, 426.42f), new Point2f(67.27f, 419.64f) }; var dst = new[] { new Point2f(270, 90), new Point2f(530, 90), new Point2f(530, -90), new Point2f(270, -90) }; using var H = Cv2.GetPerspectiveTransform(src, dst); Point2f[] mm = Cv2.PerspectiveTransform(new[] { new Point2f(61.56f, 57.38f), new Point2f(320, 240) }, H); Console.WriteLine($"{mm[0].X:F1} {mm[0].Y:F1}"); Console.WriteLine(mm[1].X > 270 && mm[1].X < 530);`, '270.0 90.0\nTrue\n');
t('watershed-13', U + `using var img = Cv2.ImRead("images/washers.png", ImreadModes.Grayscale); using var bin = img.Threshold(0, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu); using var dist = new Mat(); Cv2.DistanceTransform(bin, dist, DistanceTypes.L2, DistanceTransformMasks.Mask5); Cv2.Normalize(dist, dist, 0, 1.0, NormTypes.MinMax); using var peaks = new Mat(); Cv2.Threshold(dist, peaks, 0.45, 1.0, ThresholdTypes.Binary); using var peaks8 = new Mat(); peaks.ConvertTo(peaks8, MatType.CV_8U, 255); using var markers = new Mat(); int n = Cv2.ConnectedComponents(peaks8, markers); Console.WriteLine(n > 1); using var color = img.CvtColor(ColorConversionCodes.GRAY2BGR); Cv2.Watershed(color, markers); int labels = 0; for (int y = 0; y < markers.Rows; y += 4) for (int x = 0; x < markers.Cols; x += 4) labels = Math.Max(labels, markers.At<int>(y, x)); Console.WriteLine(labels >= 12);`, 'True\nTrue\n');
t('file-csv', U + `var lines = new List<string> { "id,area", "1,120", "2,340" }; System.IO.File.WriteAllLines("out/report.csv", lines); Console.WriteLine(System.IO.File.Exists("out/report.csv")); Console.WriteLine(System.IO.File.ReadAllText("out/report.csv").Split('\\n').Length);`, 'True\n4\n');
t('window-class', U + `using var img = Cv2.ImRead("images/sample_gray.png", ImreadModes.Grayscale); using (new Window("w1", img)) { Cv2.WaitKey(0); } var w = new Window("w2"); w.ShowImage(img); Window.WaitKey(0); Cv2.DestroyAllWindows(); Console.WriteLine("done");`, 'done\n');
t('int-parse-culture', U + `double d = double.Parse("3.5"); Console.WriteLine(d * 2); Console.WriteLine(Convert.ToInt32(2.6)); Console.WriteLine((int)2.6); Console.WriteLine(Math.Round(2.6)); Console.WriteLine(255 / 2); Console.WriteLine(255 / 2.0); byte b = 200; b += 100; Console.WriteLine(b); int x = 7; x /= 2; Console.WriteLine(x); double avg = (1 + 2) / 2; Console.WriteLine(avg);`, '7\n3\n2\n3\n127\n127.5\n44\n3\n1\n');

const filter = process.argv[2];
let pass = 0, fail = 0;
for (const tc of tests) {
  if (filter && !tc.name.includes(filter)) continue;
  const r = await runCs(tc.code, { stdin: '21\n' });
  const ok = r.out === tc.expect && !r.error;
  if (ok) pass++; else { fail++; console.log(`✗ ${tc.name} (${r.ms}ms)\n  기대: ${JSON.stringify(tc.expect)}\n  실제: ${JSON.stringify(r.out)}${r.error ? `\n  오류: ${r.error.type}: ${r.error.message} (줄 ${r.error.line || '?'})` : ''}${r.notes.length ? '\n  노트: ' + r.notes.join(' | ') : ''}`); }
}
console.log(`\n${pass} 통과, ${fail} 실패`);
process.exit(fail ? 1 : 0);
