// OpenCvSharp 바인딩 테스트: node tools/cvtest.mjs [필터]
import { runCs } from './node-host.mjs';

const tests = [];
const t = (name, code, expect, check) => tests.push({ name, code, expect, check });
const U = 'using System;\nusing OpenCvSharp;\n';

t('imread-info', U + `var img = Cv2.ImRead("images/washers.png", ImreadModes.Grayscale); Console.WriteLine($"{img.Rows} x {img.Cols}, ch={img.Channels()}, type={img.Type()}, empty={img.Empty()}"); Console.WriteLine(img.Size()); Console.WriteLine(img.Get<byte>(10, 10) >= 0);`, '480 x 640, ch=1, type=CV_8UC1, empty=False\n(width:640 height:480)\nTrue\n');
t('threshold-count', U + `var img = Cv2.ImRead("images/washers.png", ImreadModes.Grayscale); var bin = new Mat(); double t = Cv2.Threshold(img, bin, 0, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu); var labels = new Mat(); int n = Cv2.ConnectedComponents(bin, labels); Console.WriteLine($"otsu={t} n={n - 1}"); Cv2.ImShow("bin", bin); Cv2.WaitKey(0);`, 'otsu=125 n=11\n', (r) => r.images.length === 1 && r.images[0].ch === 1);
t('color-draw', U + `var canvas = new Mat(480, 640, MatType.CV_8UC3, Scalar.Black); Cv2.Rectangle(canvas, new Rect(60, 60, 240, 160), new Scalar(0, 255, 0), 3); Cv2.Circle(canvas, new Point(450, 150), 80, Scalar.Red, -1); Cv2.Line(canvas, new Point(60, 300), new Point(580, 420), new Scalar(255, 200, 0), 2); Cv2.PutText(canvas, "OpenCV C#", new Point(60, 280), HersheyFonts.HersheySimplex, 1.2, Scalar.White, 2); Vec3b px = canvas.At<Vec3b>(150, 450); Console.WriteLine($"{px.Item0} {px.Item1} {px.Item2}"); Console.WriteLine(canvas.Get<Vec3b>(100, 100)); Cv2.ImShow("canvas", canvas);`, '0 0 255\nVec3b(0, 0, 0)\n');
t('cvtcolor-split', U + `using var img = Cv2.ImRead("images/sample_color.png"); using var hsv = new Mat(); Cv2.CvtColor(img, hsv, ColorConversionCodes.BGR2HSV); Mat[] ch = Cv2.Split(hsv); Console.WriteLine(ch.Length + " " + ch[0].Channels()); var gray = img.CvtColor(ColorConversionCodes.BGR2GRAY); Console.WriteLine(gray.Type()); Scalar m = Cv2.Mean(gray); Console.WriteLine(m.Val0 > 0); Cv2.MinMaxLoc(gray, out double mn, out double mx); Console.WriteLine(mn < mx); Cv2.MinMaxLoc(gray, out Point pmin, out Point pmax); Console.WriteLine(pmin.X >= 0);`, '3 1\nCV_8UC1\nTrue\nTrue\nTrue\n');
t('contours', U + `using System.Linq;
var img = Cv2.ImRead("images/coins_parts.png", ImreadModes.Grayscale); var bin = img.Threshold(0, 255, ThresholdTypes.Binary | ThresholdTypes.Otsu); Cv2.FindContours(bin, out Point[][] contours, out HierarchyIndex[] hier, RetrievalModes.External, ContourApproximationModes.ApproxSimple); Console.WriteLine(contours.Length); var big = contours.Where(c => Cv2.ContourArea(c) > 500).OrderByDescending(c => Cv2.ContourArea(c)).ToArray(); Console.WriteLine(big.Length); var r = Cv2.BoundingRect(big[0]); Console.WriteLine(r.Width > 0 && r.Height > 0); var m = Cv2.Moments(big[0]); Console.WriteLine(m.M00 > 0); var color = new Mat(); Cv2.CvtColor(img, color, ColorConversionCodes.GRAY2BGR); Cv2.DrawContours(color, contours, -1, Scalar.Red, 2); foreach (var c in big.Take(2)) { var rr = Cv2.MinAreaRect(c); Console.WriteLine(rr.Size.Width > 30); } Console.WriteLine(Cv2.ArcLength(big[0], true) > 100);`, '12\n12\nTrue\nTrue\nTrue\nTrue\nTrue\n');
t('filters', U + `var img = Cv2.ImRead("images/gradient_noise.png", ImreadModes.Grayscale); var blur = new Mat(); Cv2.GaussianBlur(img, blur, new Size(5, 5), 0); var med = img.MedianBlur(5); var edges = new Mat(); Cv2.Canny(blur, edges, 50, 150); Console.WriteLine(Cv2.CountNonZero(edges) > 100); var k = Cv2.GetStructuringElement(MorphShapes.Ellipse, new Size(5, 5)); var opened = new Mat(); Cv2.MorphologyEx(edges, opened, MorphTypes.Close, k); Console.WriteLine(k.Rows + "x" + k.Cols); var sx = new Mat(); Cv2.Sobel(img, sx, MatType.CV_16S, 1, 0); Console.WriteLine(sx.Type()); var abs = new Mat(); Cv2.ConvertScaleAbs(sx, abs); Console.WriteLine(abs.Type()); double psnr = Cv2.PSNR(img, blur); Console.WriteLine(psnr > 10);`, 'True\n5x5\nCV_16SC1\nCV_8UC1\nTrue\n');
t('geometry', U + `var img = Cv2.ImRead("images/sample_color.png"); var small = new Mat(); Cv2.Resize(img, small, new Size(), 0.5, 0.5); Console.WriteLine(small.Size()); var M = Cv2.GetRotationMatrix2D(new Point2f(img.Width / 2f, img.Height / 2f), 30, 1.0); Console.WriteLine(M.Rows + "x" + M.Cols + " " + M.Type()); var rot = new Mat(); Cv2.WarpAffine(img, rot, M, img.Size()); Console.WriteLine(rot.Size()); var fl = img.Flip(FlipMode.Y); Console.WriteLine(fl.Width); var roi = new Mat(img, new Rect(10, 20, 100, 50)); Console.WriteLine(roi.Size() + " " + roi.IsSubmatrix); var sub = img[new Rect(0, 0, 20, 20)]; Console.WriteLine(sub.Rows); var src = new[] { new Point2f(0, 0), new Point2f(640, 0), new Point2f(640, 480), new Point2f(0, 480) }; var dst = new[] { new Point2f(10, 10), new Point2f(600, 0), new Point2f(630, 470), new Point2f(0, 480) }; var P = Cv2.GetPerspectiveTransform(src, dst); var warped = new Mat(); Cv2.WarpPerspective(img, warped, P, img.Size()); Console.WriteLine(P.Rows);`, '(width:320 height:240)\n2x3 CV_64FC1\n(width:640 height:480)\n640\n(width:100 height:50) True\n20\n3\n');
t('pixel-loop', U + `var img = new Mat(3, 4, MatType.CV_8UC1, new Scalar(10)); img.Set<byte>(1, 2, 200); int sum = 0; for (int y = 0; y < img.Rows; y++) for (int x = 0; x < img.Cols; x++) sum += img.At<byte>(y, x); Console.WriteLine(sum); var idx = img.GetGenericIndexer<byte>(); idx[0, 0] = 5; Console.WriteLine(idx[0, 0] + " " + img.Get<byte>(0, 0)); var inv = new Mat(); Cv2.BitwiseNot(img, inv); Console.WriteLine(inv.At<byte>(1, 2)); Mat a = img + 5; Console.WriteLine(a.At<byte>(2, 2)); Mat b = img * 2.0; Console.WriteLine(b.At<byte>(1, 2)); byte[] data = img.GetArray<byte>(); Console.WriteLine(data.Length); Console.WriteLine(img.Dump());`, '310\n5 5\n55\n15\n255\n12\n[5, 10, 10, 10;\n 10, 10, 200, 10;\n 10, 10, 10, 10]\n');
t('hist-clahe', U + `var img = Cv2.ImRead("images/low_contrast.png", ImreadModes.Grayscale); var hist = new Mat(); Cv2.CalcHist(new[] { img }, new[] { 0 }, null, hist, 1, new[] { 256 }, new[] { new Rangef(0, 256) }); Console.WriteLine(hist.Rows + " " + hist.Type()); float total = 0; for (int i = 0; i < 256; i++) total += hist.At<float>(i, 0); Console.WriteLine(total); var eq = new Mat(); Cv2.EqualizeHist(img, eq); var clahe = Cv2.CreateCLAHE(2.0, new Size(8, 8)); var cl = new Mat(); clahe.Apply(img, cl); Cv2.MinMaxLoc(eq, out double mn, out double mx); Console.WriteLine(mx - mn > 200);`, '256 CV_32FC1\n307200\nTrue\n');
t('hough-template', U + `var img = Cv2.ImRead("images/coins_parts.png", ImreadModes.Grayscale); var circles = Cv2.HoughCircles(img, HoughModes.Gradient, 1, 30, 100, 20, 15, 40); Console.WriteLine(circles.Length >= 10); var board = Cv2.ImRead("images/fiducial_board.png", ImreadModes.Grayscale); var tpl = Cv2.ImRead("images/fiducial_template.png", ImreadModes.Grayscale); var res = new Mat(); Cv2.MatchTemplate(board, tpl, res, TemplateMatchModes.CCoeffNormed); Cv2.MinMaxLoc(res, out _, out double maxVal, out _, out Point maxLoc); Console.WriteLine(maxVal > 0.9); Console.WriteLine(maxLoc); var edges = Cv2.ImRead("images/bracket_edges.png", ImreadModes.Grayscale).Canny(50, 150); var lines = Cv2.HoughLinesP(edges, 1, Math.PI / 180, 80, 100, 10); Console.WriteLine(lines.Length > 0); Console.WriteLine(lines[0].P1.X >= 0);`, 'True\nTrue\n(x:32 y:24)\nTrue\nTrue\n');
t('video-sim', U + `using var cap = new VideoCapture(0); Console.WriteLine(cap.IsOpened() + " " + cap.FrameWidth); var frame = new Mat(); int n = 0; while (cap.Read(frame)) { n++; if (n == 1) Console.WriteLine(frame.Size()); Cv2.ImShow("cam", frame); if (Cv2.WaitKey(1) == 27) break; } Console.WriteLine(n);`, 'True 640\n(width:640 height:480)\n60\n', (r) => r.images.length > 0 && r.images[0].frames === 60);
t('features', U + `var img1 = Cv2.ImRead("images/parts_scene.png", ImreadModes.Grayscale); var img2 = Cv2.ImRead("images/part_template.png", ImreadModes.Grayscale); var orb = ORB.Create(300); var d1 = new Mat(); var d2 = new Mat(); orb.DetectAndCompute(img1, null, out KeyPoint[] k1, d1); orb.DetectAndCompute(img2, null, out KeyPoint[] k2, d2); Console.WriteLine(k1.Length > 10 && k2.Length > 3); var bf = new BFMatcher(NormTypes.Hamming, true); var matches = bf.Match(d1, d2); Console.WriteLine(matches.Length > 0); var outImg = new Mat(); Cv2.DrawMatches(img1, k1, img2, k2, matches, outImg); Console.WriteLine(outImg.Width == img1.Width + img2.Width);`, 'True\nTrue\nTrue\n');
t('qr', U + `var img = Cv2.ImRead("images/label_lot.png", ImreadModes.Grayscale); var qr = new QRCodeDetector(); string s = qr.DetectAndDecode(img, out Point2f[] pts); Console.WriteLine(s); Console.WriteLine(pts.Length);`, 'SN=MV-000123;LOT=A2309-117;EXP=2027-09-30\n4\n');
t('connected-ex', U + `var img = Cv2.ImRead("images/washers.png", ImreadModes.Grayscale); var bin = img.Threshold(0, 255, ThresholdTypes.BinaryInv | ThresholdTypes.Otsu); var cc = Cv2.ConnectedComponentsEx(bin); Console.WriteLine(cc.LabelCount - 1); var big = cc.GetLargestBlob(); Console.WriteLine(big.Area > 1000); foreach (var b in cc.Blobs) if (b.Label > 0 && b.Area < 100) Console.WriteLine("small"); Console.WriteLine(cc.Labels.GetLength(0));`, '11\nTrue\n480\n');
t('imwrite-read', U + `var m = new Mat(4, 4, MatType.CV_8UC3, new Scalar(1, 2, 3)); Cv2.ImWrite("out/test.png", m); Console.WriteLine(System.IO.File.Exists("out/test.png")); var back = Cv2.ImRead("out/test.png"); Console.WriteLine(back.Get<Vec3b>(0, 0));`, 'True\nVec3b(1, 2, 3)\n');
t('errors', U + `try { var img = Cv2.ImRead("images/nope.png"); Console.WriteLine(img.Empty()); var g = new Mat(); Cv2.CvtColor(img, g, ColorConversionCodes.BGR2GRAY); } catch (OpenCVException e) { Console.WriteLine("cv: " + e.Message.Contains("empty")); } var a = Cv2.ImRead("images/washers.png", ImreadModes.Grayscale); try { var g2 = new Mat(); Cv2.CvtColor(a, g2, ColorConversionCodes.BGR2GRAY); } catch (OpenCVException e) { Console.WriteLine("channels"); } try { a.Get<byte>(1000, 0); } catch (IndexOutOfRangeException) { Console.WriteLine("range"); }`, 'True\ncv: True\nchannels\nrange\n');
t('inrange-color', U + `var img = Cv2.ImRead("images/color_caps.png"); var hsv = img.CvtColor(ColorConversionCodes.BGR2HSV); var mask = new Mat(); Cv2.InRange(hsv, new Scalar(0, 100, 100), new Scalar(10, 255, 255), mask); var mask2 = new Mat(); Cv2.InRange(hsv, new Scalar(170, 100, 100), new Scalar(180, 255, 255), mask2); var red = mask | mask2; Cv2.FindContours(red, out var cs, out _, RetrievalModes.External, ContourApproximationModes.ApproxSimple); int n = 0; foreach (var c in cs) if (Cv2.ContourArea(c) > 300) n++; Console.WriteLine(n);`, '5\n');

const filter = process.argv[2];
let pass = 0, fail = 0;
for (const tc of tests) {
  if (filter && !tc.name.includes(filter)) continue;
  const r = await runCs(tc.code);
  const ok = r.out === tc.expect && !r.error && (!tc.check || tc.check(r));
  if (ok) pass++; else { fail++; console.log(`✗ ${tc.name} (${r.ms}ms)\n  기대: ${JSON.stringify(tc.expect)}\n  실제: ${JSON.stringify(r.out)}${r.error ? `\n  오류: ${r.error.type}: ${r.error.message} (줄 ${r.error.line || '?'})` : ''}${tc.check && !tc.check(r) ? '\n  추가 검사 실패: ' + JSON.stringify(r.images.map((i) => ({ n: i.name, ch: i.ch, f: i.frames }))) : ''}${r.notes.length ? '\n  노트: ' + r.notes.join(' | ') : ''}`); }
}
console.log(`\n${pass} 통과, ${fail} 실패`);
process.exit(fail ? 1 : 0);
